name: Build, Tag and Publish Docker image

on:
  release:
    types: [published]
  push:
    branches:
      - main

env:
  DOCKERHUB_IMAGE: sftp
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME  }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN  }}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get correct semvers
        id: versioning
        run: |
          latest_version=$(curl -L --fail "https://hub.docker.com/v2/repositories/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE }}/tags/?page_size=1000" | \
            jq '.results | .[] | .name' -r | \
            sed 's/latest//' | \
            sort --version-sort | \
            tail -n 1 | \
            awk -F. '{$NF = $NF + 1;} 1' OFS=. | \
            sed 's/\.$/.0/')
            echo "::set-output name=latest_version::$latest_version"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE }}:${{ steps.versioning.outputs.latest_version }}
            ghcr.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE }}:${{ steps.versioning.outputs.latest_version }}

